config/routes.rb
MusicApp::Application.routes.draw do
  get '/users/activate', to: "users#activate"
  resources :users, only: [:new, :create, :show, :index, :update] do
    patch :make_admin, to: "users#make_admin!"
    collection do
      get :activate
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :create]
  end
  resources :albums, only: [:edit, :update, :show, :destroy] do
    resources :tracks, only: [:new, :create]
  end
  resources :tracks, only: [:edit, :update, :show, :destroy] do
    resources :notes, only: [:create]
  end
  resources :notes, only: [:destroy]
  root to: 'bands#index'
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :presence => true

  belongs_to :album
  has_one :band, :through => :album
  has_many :notes
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_unless_admin, only: [:new, :edit, :create, :update, :destroy]

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @band = @track.band
    @notes = @track.notes
    @note = Note.new(:track_id => @track.id, :user_id => current_user.id)
    render :show
  end

  def new
    @albums = Album.all
    @track = Track.new
    render :new
  end

  def create
    @albums = Album.all
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @albums = Album.all
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @albums = Album.all
    @track = Track.find(params[:id])
    @track.update_attributes(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy!
    redirect_to band_albums_url(@album.band_id)
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :lyrics, :bonus)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    lined_lyrics = h(lyrics).split("\n")
    noted_lyrics = "&#9835;#{lined_lyrics.join('&#9835;')}".html_safe
    noted_lyrics
  end
end

app/views/tracks/_form.html.erb
<% url = (action == :new ? album_tracks_url(params[:album_id]) : track_url(@track))%>
<% title = (action == :new ? "New Track" : "Edit Track")%>

<h3><%=title%></h3>

<form action="<%=url%>" method="POST">
  <%= csrf_token %>
  <%= request_field("PATCH") if action == :edit %>

  <p>
  <label for="name">Track Name</label>
  <input type="text" name="track[name]" id="name" value="<%=@track.name%>">
  </p>

  <p>
  <label for="album">Album</label>
  <select name="track[album_id]">
    <%@albums.each do |album|%>
    <% this_album = album.id == @track.album_id || album.id.to_s == params[:album_id] %>
      <option value="<%=album.id%>" <%= 'selected'.html_safe if this_album%> ><%=album.name%></option>
    <% end %>
  </select>
  </p>

  <input type="radio" name="track[bonus]" value="false">Regular Track
  <input type="radio" name="track[bonus]" value="true">Bonus Track

  <p>
  <label for="lyrics">Lyrics</label>
  <textarea name="track[lyrics]" id="lyrics" rows="8" cols="50"><%=@track.lyrics%></textarea>
  </p>

  <input type="submit">
</form>

app/views/tracks/edit.html.erb
<%= render "form", :action => :edit %>

app/views/tracks/new.html.erb
<%= render "form", :action => :new %>

app/views/tracks/show.html.erb
<h1><%=@track.name%></h1>
<h2>(<%=link_to @album.name, album_url(@album)%>)</h2>
<h3>(<%=link_to @band.name, band_url(@band)%>)</h3>
<p>
<%= link_to "Add More Tracks", new_album_track_url(params[:id]) if admin?%>
</p>
<h2>Lyrics</h2>

<p>
<pre><%= ugly_lyrics(@track.lyrics)%></pre>
</p>
<br>

<%= link_to "Edit these lyrics!", edit_track_url(@track) if admin?%>
<br>

<h3>Comments</h3>
<% @notes.each do |note| %>
 <p><%=note.text%><%= button_to "Delete", note_url(note), method: :delete if admin? || current_user.id == note.user_id %></p>
<% end %>

Submit a Comment!
<%= render "notes/note" %>

<br><br>
<%= button_to "Delete This Track", track_url(@track), method: :delete if admin?%>