config/routes.rb
MusicApp::Application.routes.draw do
  get '/users/activate', to: "users#activate"
  resources :users, only: [:new, :create, :show, :index, :update] do
    patch :make_admin, to: "users#make_admin!"
    collection do
      get :activate
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :create]
  end
  resources :albums, only: [:edit, :update, :show, :destroy] do
    resources :tracks, only: [:new, :create]
  end
  resources :tracks, only: [:edit, :update, :show, :destroy] do
    resources :notes, only: [:create]
  end
  resources :notes, only: [:destroy]
  root to: 'bands#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, :presence => true

  has_many :tracks, :dependent => :destroy
  belongs_to :band
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_unless_admin, only: [:new, :edit, :create, :update, :destroy]

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
    @tracks = @album.tracks
    render :show
  end

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    @bands = Band.all
    if @album.save
      redirect_to band_url(params[:band_id])
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    @bands = Band.all
    @album.update_attributes(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy!
    redirect_to albums_url
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :live)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% url = (action == :new ? band_albums_url(params[:band_id]) : album_url(@album))%>
<% title = (action == :new ? "New Album" : "Edit Album")%>

<h1><%=title%></h1>

<form action="<%=url%>" method="POST">
  <%= csrf_token %>
  <%= request_field("PATCH") if action == :edit %>

  <p>
  <label for="name">Album Name</label>
  <input type="text" name="album[name]" id="name" value="<%=@album.name%>">
  </p>

  <p>
  <label for="band">Recording Band</label>
  <select name="album[band_id]">
    <%@bands.each do |band|%>
      <% this_band = (band.id == @album.band_id || band.id.to_s == params[:band_id]) %>
      <option value="<%=band.id%>" <%= 'selected'.html_safe if this_band%> ><%=band.name%></option>
    <% end %>
  </select>
  </p>

  <input type="radio" name="album[live]" value="true">Live Recording
  <input type="radio" name="album[live]" value="false">Studio Recording

  <input type="submit">
</form>

app/views/albums/edit.html.erb
<%= render "form", :action => :edit %>

app/views/albums/new.html.erb
<%= render "form", :action => :new %>

app/views/albums/show.html.erb
<h1><%=@album.name%></h1>
<p>
<h2>(<%= link_to @band.name, band_url(@band) %>)</h2>
<%= link_to "Add More Tracks", new_album_track_url(params[:id]) if admin?%>
</p>
<h2>Tracks</h2>

<% @tracks.each do |track| %>
  <%= link_to track.name, track_url(track)%>
  <%= button_to "(Delete)", track_url(track), method: :delete if admin?%>
  <br>
<% end %>