config/routes.rb
MusicApp::Application.routes.draw do
  get '/users/activate', to: "users#activate"
  resources :users, only: [:new, :create, :show, :index, :update] do
    patch :make_admin, to: "users#make_admin!"
    collection do
      get :activate
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :create]
  end
  resources :albums, only: [:edit, :update, :show, :destroy] do
    resources :tracks, only: [:new, :create]
  end
  resources :tracks, only: [:edit, :update, :show, :destroy] do
    resources :notes, only: [:create]
  end
  resources :notes, only: [:destroy]
  root to: 'bands#index'
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, :presence => true

  has_many :albums, :dependent => :destroy
  has_many :tracks, :through => :albums
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_unless_admin, only: [:new, :edit, :create, :update, :destroy]

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(band_params)
    if @band.save
      flash[:notice] = "Update to #{@band.name} successful!"
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy!
    redirect_to(bands_url)
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% url = (action == :new ? bands_url : band_url(@band))%>
<% title = (action == :new ? "New Band" : "Edit Band")%>

<h1><%=title%></h1>

<form action="<%=url%>" method="POST">
  <%= csrf_token %>
  <%= request_field("PATCH") if action == :edit %>

  <p>
  <label for="name">Band Name</label>
  <input type="text" name="band[name]" id="name" value="<%=@band.name%>">
  </p>

  <input type="submit">
</form>

app/views/bands/edit.html.erb
<%= render "form", :action => :edit %>

app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <%= link_to band.name, band_url(band)%>
  <%= link_to "(Add an Album)", new_band_album_url(band)%>
  <br>
<% end %>

<br>
<%= link_to "Add a Band", new_band_url %>

app/views/bands/new.html.erb
<%= render "form", :action => :new %>

app/views/bands/show.html.erb
<h1><%=@band.name%></h1>
<p>
<%= link_to "Add More Albums", new_band_album_url(params[:id]) if admin?%>
</p>
<h2>Albums</h2>

<% @albums.each do |album| %>
  <%= link_to album.name, album_url(album)%>
  <%= link_to "(Add a Track)", new_album_track_url(album) if admin?%>
  <%= button_to "Delete", album_url, method: :delete if admin?%>
  <br>
<% end %>